name: release

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name'
        required: true
      dojo_version:
        description: 'Dojo version'
        required: true
  push:
    tags:
      - 'v*'
    branches:
      - main

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get version
        id: version_info
        run: |
          # if it's a tag use it or use the input.
          if [ -n "${{ github.ref_name }}" ]; then
            echo "tag_name=${{ github.ref_name }}" >> $GITHUB_OUTPUT
          else
            echo "tag_name=${{ inputs.tag_name }}" >> $GITHUB_OUTPUT
          fi
          echo $GITHUB_OUTPUT
