name: w1

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name'
        required: true
      dojo_version:
        description: 'Dojo version'
        required: true
  push:
    tags:
      - 'v*'

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      tag_name: ${{ steps.version_info.outputs.tag_name }}
      dojo_version: ${{ steps.version_info.outputs.dojo_version }}
    steps:
      - uses: actions/checkout@v3

      - name: Extract version info
        id: version_info
        run: |
         if [[ "${{ github.ref }}" == refs/tags/* ]]; then
            # Extract tag name from ref
            echo "tag_name=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
            echo "dojo_version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          else
            # We're supposed to be in a workflow_dispatch here.
            if [ -z "${{ inputs.tag_name }}" ]; then
              echo "tag_name is empty"
              exit 1
            fi
            if [[ ! "${{ inputs.tag_name }}" =~ ^v ]]; then
              echo "tag_name must start with 'v'"
              exit 1
            fi

            TAG_NAME="${{ inputs.tag_name }}"
            if [[ ! "$TAG_NAME" =~ ^v ]]; then
              TAG_NAME="v$TAG_NAME"
            fi
            echo "tag_name=$TAG_NAME" >> $GITHUB_OUTPUT

            DOJO_VERSION="${{ inputs.dojo_version }}"
            if [[ ! "$DOJO_VERSION" =~ ^v ]]; then
              DOJO_VERSION="v$DOJO_VERSION"
            fi
            echo "dojo_version=$DOJO_VERSION" >> $GITHUB_OUTPUT

          fi

  use_values:
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - name: s1
        id: s1
        run: |
          echo ${{ needs.prepare.outputs.tag_name }}
          echo ${{ needs.prepare.outputs.dojo_version }}
