name: w1

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name'
        required: true
      dojo_version:
        description: 'Dojo version'
        required: true
  push:
    tags:
      - 'v*'
    branches:
      - main

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Extract version info
        id: version_info
        run: |
         if [[ "${{ github.ref }}" == refs/tags/* ]]; then
            # Extract tag name from ref
            echo "tag_name=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          else
            echo "tag_name=${{ inputs.tag_name }}" >> $GITHUB_OUTPUT
          fi
          echo ${{join(steps.version_info.outputs.*, '\n')}}
