name: w1

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name'
        required: true
      dojo_version:
        description: 'Dojo version'
        required: true
  push:
    tags:
      - 'v*'

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      tag_name: ${{ steps.version_info.outputs.tag_name }}
      dojo_version: ${{ steps.version_info.outputs.dojo_version }}
    steps:
      - uses: actions/checkout@v3

      - name: Extract version info
        id: version_info
        run: |
         if [[ "${{ github.ref }}" == refs/tags/* ]]; then
            # Extract tag name from ref
            echo "tag_name=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
            echo "dojo_version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          else
            # We're supposed to be in a workflow_dispatch here.
            if [ -z "${{ inputs.tag_name }}" ]; then
              echo "tag_name is empty"
              exit 1
            fi
            echo "tag_name=${{ inputs.tag_name }}" >> $GITHUB_OUTPUT
            echo "dojo_version=${{ inputs.dojo_version }}" >> $GITHUB_OUTPUT
          fi

  use_values:
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - name: s1
        id: s1
        run: |
          echo ${{ needs.prepare.outputs.tag_name }}
          echo ${{ needs.prepare.outputs.dojo_version }}
