name: w1

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name'
        required: true
      dojo_version:
        description: 'Dojo version'
        required: true
  push:
    tags:
      - 'v*'

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Extract version info
        id: version_info
        run: |
         if [[ "${{ github.ref }}" == refs/tags/* ]]; then
            # Extract tag name from ref
            echo "tag_name=${GITHUB_REF#refs/tags/}" >> /tmp/version_info
          else
            # We're supposed to be in a workflow_dispatch here.
            if [ -z "${{ inputs.tag_name }}" ]; then
              echo "tag_name is empty"
              exit 1
            fi
            echo "tag_name=${{ inputs.tag_name }}" >> /tmp/version_info
          fi
          cat /tmp/version_info

          cat /tmp/version_info >> $GITHUB_OUTPUT

  use:
    needs: version_info
    runs-on: ubuntu-latest
    steps:
      - name: s1
        id: s1
        run: |
          echo ${{ needs.version_info.outputs.tag_name }}
