name: w2

on:
  pull_request:
    paths:
      - 'dir1/**'

  push:
    paths:
      - 'dir1/**'

jobs:
  j1:
    runs-on: ubuntu-latest
    #if: "!contains(github.event.head_commit.message, '(docker)')"

    steps:
      - uses: actions/checkout@v3
      - name: S1
        id: s1
        run: |
          echo "Hello, world!"
